### ISSUE TITLE
Hessian 反序列化知一二 | 素十八

### ISSUE THREAD

**Issue by su18** [su18/blogtalk#48]
https://su18.org/post/hessian/#%E4%B9%9D-%E5%8F%82%E8%80%83 

 你救赎的人 终将成为你的光

**Comment by zzzskd** [comment]
师傅请问下Resin链、XBean 链中，关于 XString 的处理有介绍嘛，看着截图里面有说对碳基生物有些超前==  

我在复现 Resin 链时发现如果 `new QName` 将` first` 还有 `rest` 字符串长度都小于3时(比如 `QName qName = new QName(continuationDirContext, "a", "b"); ` )，虽然经过 `marshalsec.gadgets.ToStringUtil#unhash` 处理，依然会导致在 `java.util.HashMap#putVal` 里面 `Xstring` 和 `QName` 的hash不一样, 不能执行 `XString.equals`方法

还请师傅指教

**Comment by su18** [comment]
> 师傅请问下Resin链、XBean 链中，关于 XString 的处理有介绍嘛，看着截图里面有说对碳基生物有些超前==
> 
> 我在复现 Resin 链时发现如果 `new QName` 将` first` 还有 `rest` 字符串长度都小于3时(比如 `QName qName = new QName(continuationDirContext, "a", "b"); ` )，虽然经过 `marshalsec.gadgets.ToStringUtil#unhash` 处理，依然会导致在 `java.util.HashMap#putVal` 里面 `Xstring` 和 `QName` 的hash不一样, 不能执行 `XString.equals`方法
> 
> 还请师傅指教

第一个问题，文章里一笔带过，XString 的 `equals()` 方法会调用其封装类的 `toSting()` 方法， 作为中间链存在，前面可以用 HashMap 触发，后面可以触发 Qname/ReadOnlyBinding 等 `toString()` 方法中的逻辑。

第二个问题，我对 HashMap put 影响处理的“碳基超前”写法其实不具有通用性，只能在部分版本 JDK 使用，具体分析可以参考链接：[https://su18.org/post/ysoserial-su18-1/#urldns](https://su18.org/post/ysoserial-su18-1/#urldns)，此举是为了解决触发反序列化利用之前使用 put 方法将类放入 HashMap 带来的一系列影响，例如 hashCode 缓存等，在某些链中，甚至还会提前触发利用链，这部分 ysoserial 和 marshalsec 自身的实现方式要比我学习的时候写的测试代码要更好，所以可以忽略。

第三个问题，实际涉及到的可以称之为 “HashCode碰撞”，`java.util.HashMap#putVal` 方法在 key 的 hashCode 一致的时候会触发 equals 方法调用，XString 的 hashCode 比较有意思，会将其封装的类强转为 String 类型再调用 hashCode 方法，而利用 String 类型的 hashCode ，就可以碰撞出任意 HashCode，可以参考这篇文章 [https://paper.seebug.org/199/#hashcode](https://paper.seebug.org/199/#hashcode)，实际上代码与 `marshalsec.gadgets.ToStringUtil#unhash` 这个方法的代码也是一致的，但是这个具体的碰撞流程我没跟过，至于你提出的问题，我猜测可能是在字符串较短时，相关的逻辑失效，导致计算的结果不一致，你可以单独将这部分拿出来测试下试试

**Comment by zzzskd** [comment]
> @su18
> > 师傅请问下Resin链、XBean 链中，关于 XString 的处理有介绍嘛，看着截图里面有说对碳基生物有些超前==
> > 
> > 我在复现 Resin 链时发现如果 `new QName` 将` first` 还有 `rest` 字符串长度都小于3时(比如 `QName qName = new QName(continuationDirContext, "a", "b"); ` )，虽然经过 `marshalsec.gadgets.ToStringUtil#unhash` 处理，依然会导致在 `java.util.HashMap#putVal` 里面 `Xstring` 和 `QName` 的hash不一样, 不能执行 `XString.equals`方法
> > 
> > 还请师傅指教
> 
> 第一个问题，文章里一笔带过，XString 的 `equals()` 方法会调用其封装类的 `toSting()` 方法， 作为中间链存在，前面可以用 HashMap 触发，后面可以触发 Qname/ReadOnlyBinding 等 `toString()` 方法中的逻辑。
> 
> 第二个问题，我对 HashMap put 影响处理的“碳基超前”写法其实不具有通用性，只能在部分版本 JDK 使用，具体分析可以参考链接：[https://su18.org/post/ysoserial-su18-1/#urldns](https://su18.org/post/ysoserial-su18-1/#urldns)，此举是为了解决触发反序列化利用之前使用 put 方法将类放入 HashMap 带来的一系列影响，例如 hashCode 缓存等，在某些链中，甚至还会提前触发利用链，这部分 ysoserial 和 marshalsec 自身的实现方式要比我学习的时候写的测试代码要更好，所以可以忽略。
> 
> 第三个问题，实际涉及到的可以称之为 “HashCode碰撞”，`java.util.HashMap#putVal` 方法在 key 的 hashCode 一致的时候会触发 equals 方法调用，XString 的 hashCode 比较有意思，会将其封装的类强转为 String 类型再调用 hashCode 方法，而利用 String 类型的 hashCode ，就可以碰撞出任意 HashCode，可以参考这篇文章 [https://paper.seebug.org/199/#hashcode](https://paper.seebug.org/199/#hashcode)，实际上代码与 `marshalsec.gadgets.ToStringUtil#unhash` 这个方法的代码也是一致的，但是这个具体的碰撞流程我没跟过，至于你提出的问题，我猜测可能是在字符串较短时，相关的逻辑失效，导致计算的结果不一致，你可以单独将这部分拿出来测试下试试

感谢师傅解答，我试下😆

**Comment by qingege888** [comment]
师傅请教下，我在复现SpringAbstractBeanFactoryPointcutAdvisor链时，抛出了如下异常：
Exception in thread "main" java.lang.IllegalStateException: 'adviceBeanName' must be specified
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.aop.support.AbstractBeanFactoryPointcutAdvisor.getAdvice(AbstractBeanFactoryPointcutAdvisor.java:111)
	at org.springframework.aop.support.AbstractPointcutAdvisor.equals(AbstractPointcutAdvisor.java:76)
	at java.util.HashMap.putVal(HashMap.java:635)
	at java.util.HashMap.put(HashMap.java:612)
	at com.caucho.hessian.io.MapDeserializer.readMap(MapDeserializer.java:114)
	at com.caucho.hessian.io.SerializerFactory.readMap(SerializerFactory.java:522)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1160)
	at nc.bs.framework.js.rmi.SpringAbstractBeanFactoryPointcutAdvisortest.main(SpringAbstractBeanFactoryPointcutAdvisortest.java:62)
我的环境是
java version "1.8.0_202"
spring-aop-5.3.20.jar
spring-beans-5.3.20.jar
spring-context-5.3.20.jar
spring-core-5.3.20.jar
spring-expression-5.3.20.jar
spring-web-5.3.20.jar
spring-webmvc-5.3.20.jar
hessian-3.1.3.jar

尝试调试跟踪没有找到原因.....POC参考这个链接：https://zhuanlan.zhihu.com/p/448398658
请教师傅是否遇到这个情况，这是啥原因......谢谢

**Comment by EndlessShw** [comment]
> 这里由于篇幅原因（懒癌），这里就不一一分析各个利用链了，只是大概说一下利用链和一些关键触发点，详细的利用测试代码和注释已经更新到 [ysoserial](https://github.com/su18/ysoserial) 学习项目中。

请问师傅，该学习项目似乎已经没了，请问还有吗？QAQ

**Comment by KaGty1** [comment]
想问下师傅，Hessian_Rome链，二次反序列化调用TemplatesImpl.getOutProperties那里，获取getter方法的顺序中，我的电脑里getStylesheetDOM()方法的调用是要在getOutProperties方法之前的，这就会导致空指针错误，进而无法进行命令执行。我之前有关注过Jackson利用链具有不稳定性的相关文章 https://pankas.top/2023/10/04/%E5%85%B3%E4%BA%8Ejava%E5%8F%8D%E5%BA%8F%E5%88%97%E5%8C%96%E4%B8%ADjackson%E9%93%BE%E5%AD%90%E4%B8%8D%E7%A8%B3%E5%AE%9A%E9%97%AE%E9%A2%98/#%E6%A0%B9%E6%9C%AC%E5%8E%9F%E5%9B%A0 ，使用了动态代理来解决getter调用顺序的问题，我注意到Hessian中并没有师傅提出过这个说法，特来请教师傅

**Comment by alZerNest** [comment]
> @EndlessShw
> > 这里由于篇幅原因（懒癌），这里就不一一分析各个利用链了，只是大概说一下利用链和一些关键触发点，详细的利用测试代码和注释已经更新到 [ysoserial](https://github.com/su18/ysoserial) 学习项目中。
> 
> 请问师傅，该学习项目似乎已经没了，请问还有吗？QAQ

https://github.com/unchihuoguo/ysoserial?tab=readme-ov-file

**Comment by EndlessShw** [comment]
> > [@EndlessShw](https://github.com/EndlessShw)
> > > 这里由于篇幅原因（懒癌），这里就不一一分析各个利用链了，只是大概说一下利用链和一些关键触发点，详细的利用测试代码和注释已经更新到 [ysoserial](https://github.com/su18/ysoserial) 学习项目中。
> > 
> > 
> > 请问师傅，该学习项目似乎已经没了，请问还有吗？QAQ
> 
> https://github.com/unchihuoguo/ysoserial?tab=readme-ov-file

谢谢师傅，但是我已经转开发了，祝师傅在安全的仕途上步步高升！

**Comment by alZerNest** [comment]
> > > [@EndlessShw](https://github.com/EndlessShw)
> > > > 这里由于篇幅原因（懒癌），这里就不一一分析各个利用链了，只是大概说一下利用链和一些关键触发点，详细的利用测试代码和注释已经更新到 [ysoserial](https://github.com/su18/ysoserial) 学习项目中。
> > > 
> > > 
> > > 请问师傅，该学习项目似乎已经没了，请问还有吗？QAQ
> > 
> > https://github.com/unchihuoguo/ysoserial?tab=readme-ov-file
> 
> 谢谢师傅，但是我已经转开发了，祝师傅在安全的仕途上步步高升！

好的，师傅你也是，一起加油(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ
